// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalculateCIN(arg1) {
  return window['go']['main']['App']['CalculateCIN'](arg1);
}

export function GenerateRandomAWB() {
  return window['go']['main']['App']['GenerateRandomAWB']();
}
